### ISSUE TITLE
Multiple Render Api's At Once

### ISSUE THREAD

**Issue by JonahGoldsmith** [jochumdev/TheForgeCMake#5]
With the current way this cmake project is setup it looks like only one renderer is available at a time and it is decided during build time. It should be possible on a platform like Windows to support hot swapping from D3D12 -> Vulkan at Runtime like the examples support. But with this configuration only one renderer can be used at once. Let me know if I am mistaken as I only went through the projects CMake Files.

**Comment by JonahGoldsmith** [comment]
Other than this above comment, this looks like a much more complete version of the other CMake ports for the Forge!

**Comment by jochumdev** [comment]
Hey @JonahGoldsmith 

Thanks for the fast response! Thats nice.

Yes, you'r right currently one renderer per build is supported. I'll fix that soon.

Kind regards,
René
